; TODO INSERT CONFIG CODE HERE USING CONFIG BITS GENERATOR
 #include "p16f15376.inc"

; CONFIG1
; __config 0xFFFA
 __CONFIG _CONFIG1, _FEXTOSC_XT & _RSTOSC_EXT1X & _CLKOUTEN_OFF & _CSWEN_ON & _FCMEN_ON
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _MCLRE_ON & _PWRTE_OFF & _LPBOREN_OFF & _BOREN_ON & _BORV_LO & _ZCD_OFF & _PPS1WAY_ON & _STVREN_ON
; CONFIG3
; __config 0xFFFF
 __CONFIG _CONFIG3, _WDTCPS_WDTCPS_31 & _WDTE_ON & _WDTCWS_WDTCWS_7 & _WDTCCS_SC
; CONFIG4
; __config 0xFFFF
 __CONFIG _CONFIG4, _BBSIZE_BB512 & _BBEN_OFF & _SAFEN_OFF & _WRTAPP_OFF & _WRTB_OFF & _WRTC_OFF & _WRTSAF_OFF & _LVP_ON
; CONFIG5
; __config 0xFFFF
 __CONFIG _CONFIG5, _CP_OFF
 
CONT_INT   EQU	    0x20

    ORG	    0x00
    GOTO    START                   ; go to beginning of program
    ORG	    0x04
    GOTO    ISR_ROUTINE

; TODO ADD INTERRUPTS HERE IF USED

;MAIN_PROG CODE                      ; let linker place main program
    ORG 0x10
START
    MOVLW	0x3D		    ;NUMBER OF OVERFLOWS TO CHANGE STATE OF LED
    MOVWF	CONT_INT
    BANKSEL	TRISB
    MOVLW	0XFE		    ;set RB0 as output
    MOVWF	TRISB
    MOVLW	0x00
    MOVWF	PORTB		    ;CLEAR PORTB BITS
    BANKSEL	T0CON0
    MOVLW	0X80
    MOVWF	T0CON0		    ;ENABLES TIMER0 MODULE, 8-BITS MODE
    BANKSEL	T0CON1
    MOVLW	0X46
    MOVWF	T0CON1		    ;CLOCK SOURCE: FOSC/4; PRESCALER: 1/64
    BANKSEL	PIE0
    MOVLW	0X20
    MOVWF	PIE0
    ;BSF		PIE0,TMR0IE	    ;ENABLE TIMER0 INTERRUPTION
    ;BANKSEL	PIR0
    ;BCF		PIR0,TMR0IF	    ;CLEAR FLAG
    ;BANKSEL	INTCON
    MOVLW	0xC0
    MOVWF	INTCON
    ;BSF		INTCON,GIE	    ;ENABLE GLOBAL INTERRUPTION
LOOP
    NOP
    GOTO	LOOP	    ;WHILE (1)

ISR_ROUTINE
    DECFSZ	CONT_INT
    GOTO	RET_ISR
    MOVLW	0x01
    XORWF	PORTB,W
    MOVLW	0x46
    MOVWF	CONT_INT
    GOTO	RET_ISR
    
    
RET_ISR
    BANKSEL PIR0
    MOVLW   0X00    ;Clear TRM0IF
    MOVWF   PIR0
    RETFIE
    
    


    END
